before_commands:
    - pip3 install networkx # Python3

checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    external_code_coverage: true
    pylint:
        python_version: 3
        config_file: '.pylintrc'
