site_name: grortir
site_description: Application for supporting optimization of production process.
site_author: Wojtek Pietrucha
repo_url: https://github.com/qbahn/grortir
# google_analytics: ['XX-XXXXXXXX-XX', 'auto']

theme: readthedocs

pages:
- Home: index.md
- Getting Started: gettingStarted.md
- Code:
  - Classes: code/classes.md
  - Packages: code/packages.md
  - ApiDocs: code/apidocs.md
- About:
  - 'Release Notes': about/CHANGES.md  # Copied automaticly from root dir.
  - Contributing: about/contributing.md
  - License: about/license.md
